Repository kubernetes-sigs/nat64, pull requests merged in 2025-03, with the labels that each got.

#9 Update README.md
  README.md
Labels: approved, lgtm, cncf-cla: yes, ok-to-test, size/S

#13 configure all CIDRs and fix image build
  Makefile
  README.md
  bpf/include/lib/config.h
  bpf/include/lib/ip.h
  main.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#14 Do not build locally for releasing the image
  Makefile
Labels: approved, lgtm, cncf-cla: yes, size/XS

#15 Add ensure-buildx to make release for multiarch build
  Makefile
  hack/init-buildx.sh
Labels: size/M, approved, lgtm, cncf-cla: yes

#16 Make hack/init-buildx.sh executable
  hack/init-buildx.sh
Labels: cncf-cla: yes, size/XS
