Repository kubernetes-sigs/nat64, pull requests merged in 2025-04, with the labels that each got.

#17 use netlink for nftables
  .github/workflows/e2e.yml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  bpf/include/lib/config.h
  bpf/include/lib/csum.h
  bpf/include/lib/icmp.h
  bpf/include/lib/ip.h
  bpf/nat64.c
  go.mod
  go.sum
  hack/lint.sh
  install.yaml
  main.go
  main_test.go
Labels: approved, size/XXL, cncf-cla: yes

#18 Update README.md
  README.md
Labels: approved, cncf-cla: yes, size/XS

#23 E2e tests
  .github/workflows/bats.yml
  .github/workflows/e2e.yml
  bpf/nat64.c
  kind-ipv6.yaml
  main.go
  main_test.go
  tests/README.md
  tests/e2e.bats
  tests/setup_suite.bash
Labels: approved, cncf-cla: yes, size/L

#24 Update README with project prerequisites
  README.md
Labels: cncf-cla: yes, size/XS

#25 stabilize tests
  tests/setup_suite.bash
Labels: approved, cncf-cla: yes, size/XS

#29 Add more e2e tests
  .github/workflows/bats.yml
  install.yaml
  tests/e2e.bats
  tests/setup_suite.bash
Labels: size/M, approved, lgtm, cncf-cla: yes
